name: Publish Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-build-a-server-gpr:
    name: Publish build-a-server to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@tenna-llc'
      - run: npm ci --only=production
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm ls --depth=0
      - run: cp ./docker/build-a-server/Dockerfile ./Dockerfile
      - uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{secrets.GITHUB_TOKEN}}
          imageName: hapi-server-build-a-server
  publish-migration-gpr:
    name: Publish aemp-migration to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@tenna-llc'
      - run: npm ci --only=production
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm ls --depth=0
      - run: cp ./docker/migration-server/Dockerfile ./Dockerfile
      - uses: matootie/github-docker@v2.2.2
        with:
          accessToken: ${{secrets.GITHUB_TOKEN}}
          imageName: migration
